// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfuuelkswultbitktyhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmdXVlbGtzd3VsdGJpdGt0eWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNDczMTIsImV4cCI6MjA1NzgyMzMxMn0.VeezgonxZxfNoubTujRU_fBziq0ENKVQdIgRconYlYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);